# Week 9 Lecture 2
## pandas
- [pandas](https://pandas.pydata.org/) is a Python library for working with DataFrames, the Pyret equivalent of a Table

In [3]:
import pandas as pd

A Pyret table:
```arr
orders = table: date, dish, quantity, order_type
  row: "2023-07-01", "Pasta", 2, "dine-in"
  row: "2023-07-01", "Salad", 1, "takeout"
end
```
- pandas DataFrame

In [4]:
data = {
    'date': ['2023-07-01', '2023-07-01', '2023-07-02'],
    'dish': ['Pasta', 'Salad', 'Burger'],
    'quantity': [2, 1, 3],
    'order_type': ['dine-in', 'takeout', 'dine-in']
}

orders = pd.DataFrame(data)

## Loading and Accessing Data
- pandas provides the `read_csv` method for loading CSV files


Loading in Pyret
```arr
orders = load-table: date, dish, quantity, order_type
  source: csv-table-file("orders.csv", default-options)
end
```

In [5]:
orders = pd.read_csv("orders.csv")

- You can view the first five rows with the `head()` method and the last five with `tail()`

In [6]:
orders.head()

         date    dish  quantity order_type
0  2026-07-01   Pasta         2    dine-in
1  2026-07-01   Salad         1    takeout
2  2026-07-02  Burger         6    dine-in
3  2026-07-02   Pasta         2    dine-in
4  2026-07-03   Chips         1    takeout

In [7]:
orders.tail()

         date    dish  quantity order_type
0  2026-07-01   Pasta         2    dine-in
1  2026-07-01   Salad         1    takeout
2  2026-07-02  Burger         6    dine-in
3  2026-07-02   Pasta         2    dine-in
4  2026-07-03   Chips         1    takeout

- Rows can be accessed using the `iloc` accessor and square bracket notation for row numbers

Pyret way:
```arr
orders.row-n(1)["dish"]
```

In [19]:
orders.iloc[1]

date          2026-07-01
dish               Salad
quantity               1
order_type       takeout
Name: 1, dtype: object

In [21]:
orders.iloc[1]["dish"]

'Salad'

- Extracting Columns as Lists

Pyret way:
```arr
quantities = orders.get-column("quantity")
```

In [10]:
quantities = orders['quantity']

- There are methods for computing statistics from a columns

Pyret way:
```arr
mean(orders, "quantity")    # Direct table operation
sum(orders, "quantity")     # Direct table operation
```

In [11]:
orders['quantity'].mean()

np.float64(2.4)

In [12]:
orders['quantity'].sum()

np.int64(12)

- You can get a Series of unique values using the [unique](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.unique.html#pandas.Series.unique) method

In [13]:
orders['order_type'].unique()

array(['dine-in', 'takeout'], dtype=object)

- We can get `value_counts` of columns with categorical values

In [14]:
orders['order_type'].value_counts()

order_type
dine-in    3
takeout    2
Name: count, dtype: int64

## Filtering
pandas uses boolean based filtering to select values from a Series

In [15]:
orders['order_type'] == "dine-in"

0     True
1    False
2     True
3     True
4    False
Name: order_type, dtype: bool

A Series of booleans can be used to select from the original DataFrame

In [16]:
orders[orders['order_type'] == "dine-in"]

         date    dish  quantity order_type
0  2026-07-01   Pasta         2    dine-in
2  2026-07-02  Burger         6    dine-in
3  2026-07-02   Pasta         2    dine-in

They can be combined using the `&` operator

In [17]:
orders[(orders['order_type'] == "dine-in") & (orders['dish'] == "Pasta")]

         date   dish  quantity order_type
0  2026-07-01  Pasta         2    dine-in
3  2026-07-02  Pasta         2    dine-in

We can use the `.isn` to check membership of a list

In [18]:
orders['dish'].isin(["Burger", "Chips"])

0    False
1    False
2     True
3    False
4     True
Name: dish, dtype: bool

## Class Exercises
### Creating and Loading DataFrames
- Create a DataFrame manually with `workouts` data `activity` and `duration`. Make at least 5 rows.

In [26]:
data = {
    'activity': ['run', 'swim', 'bike', 'weightlift', 'yoga'],
    'duration': [30, 45, 67, 78, 30]
}

workouts = pd.DataFrame(data)

- Load the CSV from `photos.csv` into a DataFrame. Print the first 5 rows.

In [27]:
photos = pd.read_csv("photos.csv")

photos.head()

                        Location   Subject        Date
0                   Cairo, Egypt  Portrait  2023-08-15
1                     London, UK  Mountain  2024-09-14
2                    Rome, Italy      Food  2021-10-14
3  Yellowstone National Park, WY   Concert  2024-05-31
4                   Tokyo, Japan      Food  2024-01-16

### Accessing Data
- Get the second row from your `workouts` DataFrame (remember: Python uses 0-based indexing).

In [28]:
workouts.iloc[0]

activity    run
duration     30
Name: 0, dtype: object

- Extract the `activity` column and print all unique activity names.

In [29]:
print(workouts['activity'].unique())

['run' 'swim' 'bike' 'weightlift' 'yoga']

- Get the duration value from the third workout (combining row and column access).

In [31]:
print(workouts.iloc[2]['duration'])

67

- What happens if you try to access a row that doesn't exist? Try it and note the error.

In [33]:
# workouts.iloc[6]
# Returns saying that signle positional indexer is out-of-bounds

- What happens if you try to access a column that doesn't exist? Try it and note the error.

In [35]:
# workouts['time']
# Returns a message that declares that the column could not be found and does not exist

### Extracting Columns & Statistics
- Extract the `duration` column from your `workouts` DataFrame and store it in a variable called `durations`.

In [36]:
duration = workouts['duration']

- Work with the `durations` Series to find: `.mean()`, `.sum()`, `.max()`, `.min()`.

In [38]:
print(duration.mean())

print(duration.sum())

print(duration.max())

print(duration.min())

50.0
250
78
30

- Calculate the `range` (difference between `max` and `min`) of workout durations.

In [39]:
ran = duration.max() - duration.min()

print(ran)

48

- Get the value counts of the `Subject` from the `photos` DataFrame
- Calculate its median number of photos per subject using `.median()`

In [44]:
value_count = photos['Subject'].value_counts()
value_count

Subject
Concert           11
Forest             9
Birthday party     9
Wedding            8
Mountain           7
Festival           7
Street art         7
Sunset             7
Food               6
City skyline       6
Portrait           5
Wildlife           5
Museum exhibit     5
Architecture       4
Beach              4
Name: count, dtype: int64

In [45]:
print(value_count.median())

7.0